name: Django Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies and DB migrations
        env:
          SQL_ENGINE: django.db.backends.sqlite3
          DB_NAME: fusion
          SECRET_KEY: cj_u51f&4^7t7v=-%=cxo7y$wi)n!44$x4$3y&$$a*y)@ghkom'
        run: |
          echo "DB_ENGINE: $DB_ENGINE"
          echo "DB_NAME: $DB_NAME"
          echo "DB_USER: $DB_USER"
          echo "DB_PASSWORD: $DB_PASSWORD"
          echo "DB_HOST: $DB_HOST"
          echo "DB_PORT: $DB_PORT"
          
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate

      - name: Lint with flake8
        run: |
          python -m flake8 .

      - name: Blue check
        run: |
          python -m blue --check --diff . |
          python -m blue .

      - name: Isort check
        run: |
          python -m isort . --skip migrations

      - name: Coverage report
        env:
          SQL_ENGINE: django.db.backends.sqlite3
          DB_NAME: fusion
          SECRET_KEY: cj_u51f&4^7t7v=-%=cxo7y$wi)n!44$x4$3y&$$a*y)@ghkom'
        run: |
          coverage run manage.py test
          coverage report

      - name: Django Testing
        run: |
          python manage.py test 
