name: Django Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          python -m flake8 .

      - name: Blue check
        run: |
          python -m blue --check --diff .
          python -m blue .

      - name: Isort check
        run: |
          python -m isort --check --diff .
          python -m isort .

      - name: Coverage report
        run: |
          coverage run manage.py test
          coverage report

      - name: Django Testing
        run: |
          python manage.py test 
